### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por Id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=RoMANCE

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "THE MOON",
  "year": 2024,
  "director": "Elon Musk",
  "duration": 100,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Crime", "Drama"],
  "rate": 0.0
}

### Actualizar una película
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2023
}
